### ISSUE TITLE
Customize color

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#10]
Is it possible for you to make a customize option for the non hosts to change their color. I tried to make it before but i didnt work.

**Comment by Twometer** [comment]
Yes I can do that, the functionality is in place and even the button. I was just too lazy to make the customize UI work with that 😂 but I'll look into it in the next couple of days

**Comment by vivandoshi08** [comment]
Also can you make a minimap?

**Comment by vivandoshi08** [comment]
It gets very confusing to get around the map otherwise, especially for beginners to the game.

**Comment by Twometer** [comment]
Yes but please open a new issue for this. 
Along with the minimap, the admin table could also be implemented. 
Also I curently have

**Comment by Twometer** [comment]
I currently have classes so maybe you can try to start with the minimap? :)

**Comment by Twometer** [comment]
v2 can do color customization for everyone
