### ISSUE TITLE
Gson error

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#13]
When running the game, I get the error
![Screenshot (22)](https://user-images.githubusercontent.com/41412103/100901925-3af8c080-3479-11eb-8f9c-7ff1c5bd7ff9.png)

**Comment by Twometer** [comment]
There's probably something wrong with the config file (located at `%userprofile%\Among Us 3D\settings.json`

Can you attach that file here so I can take a look at the bug?

**Comment by vivandoshi08** [comment]
Thank you for helping me find the location. I fixed the error. The problem was that there was two s's that weren't supposed to be there. Must have been a typo by me.
