### ISSUE TITLE
Option to disable sounds

### ISSUE THREAD

**Issue by daniel-lerch** [Twometer/among-us-3d#2]
Among Us 3D already produces very accurate sounds which even match the current scene but sometimes you don't want a game to make noise especially if you're a developer and have to instances running at a time. Some sliders for sound volumes shouldn't be too much work with your current UI framework 😉

**Comment by Twometer** [comment]
I actually wanted to add that, however I couldn't find a way to control the master volume with OpenAL. If you find a way to do that, I'll be happy to implement that :P
