### ISSUE TITLE
Error when running game from source. 

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#6]
After building the code with gradle and installing the libraries from gradle, an error comes about neko engine not being installed. 
![Screenshot (15)](https://user-images.githubusercontent.com/41412103/99895864-d26f3f80-2c3f-11eb-8e3d-de702e9bafd6.png)
#5

**Comment by Twometer** [comment]
Oops, sorry. My maven server was not running, can you try again?

**Comment by vivandoshi08** [comment]
The maven server works now, but there is an issue with Ultralight. 
![Screenshot (17)](https://user-images.githubusercontent.com/41412103/99915423-6ed52880-2cb8-11eb-9429-100367147411.png)

**Comment by Twometer** [comment]
The contents of the bin folder should be directly inside the Ultralight folder, like this:
![image](https://user-images.githubusercontent.com/26793103/99920272-ac6e9b80-2d22-11eb-820e-51a1a86be7ed.png)

**Comment by vivandoshi08** [comment]
Perfect. Now I can run it from source. Thanks for the help and will keep you all updated on things like cameras.

**Comment by vivandoshi08** [comment]
Would just like to ask, how can i also make the installer .exe or .app from source.

**Comment by Twometer** [comment]
To build an installer, you need [Launch4J ](http://launch4j.sourceforge.net/) and [Inno Setup](https://jrsoftware.org/isinfo.php). Then, the `build.ps1` PowerShell script should do the rest.

**Comment by vivandoshi08** [comment]
Is it possible to make the installer for macos?

**Comment by daniel-lerch** [comment]
The current installer is based on [Inno Setup 6](https://jrsoftware.org/isinfo.php) which only works on Windows. For macOS you would definitely need a different packaging but I'm not even sure whether the [Neko Engine](https://github.com/Twometer/neko-engine) would run on macOS without modifications. However, if you really need macOS support you should open a separate issue for that.

**Comment by Twometer** [comment]
The neko engine currently only imports the Windows LWJGL binaries, but it could be made to work on Linux/Mac

**Comment by vivandoshi08** [comment]
do you recommend i just use something like wine then, or is there any way i could make it native for macos.

**Comment by Twometer** [comment]
I don't know if Wine supports Java and the OpenGL API which is used by LWJGL, but you can of course try it.

However, to make a version of this game for macOS, I'd have to release a mac version of the neko engine, and then use that in Among Us. Then, for a native installer, maybe something like [this](http://izpack.org/) could be used.

**Comment by vivandoshi08** [comment]
Do you think you will be able to release a new mac version of neko engine or is that too much work?

**Comment by Twometer** [comment]
It should actually not be much work to change that, however the newest macOS device I have is a 2009 macbook pro and I have my doubts that it will run this game, so I can't really test it.

**Comment by vivandoshi08** [comment]
Not to pressure you or anything, but i tested it on wine and it worked really well. I also have the same mac version as you so i have feeling that it might work.

**Comment by vivandoshi08** [comment]
Also is there a way to make this a jar, because then it will be easy to convert.

**Comment by daniel-lerch** [comment]
You can run `./gradlew jar` or `.\gradlew.bat jar` on Windows to create a .jar file. That file however, won't be portable to macOS oder Linux because it only contains the native LWJGL libraries for Windows.

**Comment by vivandoshi08** [comment]
is there a way where i could possibly download the libraries to mac and then set up the neko engine from maven to work with my mac libraries?

**Comment by Twometer** [comment]
I would have to do testing to verify that that's the only thing it needs, but in the neko engine's build.gradle file line 10, you'd need to change `project.ext.lwjglNatives = "natives-windows"` to `project.ext.lwjglNatives = "natives-macos`, and then rebuild. Of course, you'd also need to replace the Windows DLL Ultralight folder with the macos version

**Comment by daniel-lerch** [comment]
I opened a new issue for a clean integration of native libraries at Twometer/neko-engine#2

**Comment by Twometer** [comment]
I'd also like a new issue in this project for further discussion of cross-platform support
