### ISSUE TITLE
How to host the game on a server

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#7]
How do i host the game on a server like aws.

**Comment by Twometer** [comment]
By default the game connects to my "public" game server. To host it on a different one you need the jar File and run it with --server. Then you can change the client config to connect to the new server ip

**Comment by vivandoshi08** [comment]
if i made any changes to the game, will they still be there if it connects to your public server?

**Comment by Twometer** [comment]
yes they will, but only if you don't make server-side changes too. those won't be on the upstream server

**Comment by vivandoshi08** [comment]
what are some examples of server-side changes??

**Comment by Twometer** [comment]
Any protocol changes (e.g. changes to the NetMessage.java file) or changes to anything under the net/server package.

**Comment by vivandoshi08** [comment]
ok thanks.
This means things like added camera function doesnt need a new server?

**Comment by Twometer** [comment]
You're welcome. 
Exactly, for the cams you don't need a new server. Only if you'd want to add actual blinking cams into the world, like the real game has. But I'd probably define a new camera player controller and UI screen and just teleport the player's viewport camera to all the cam locations in the actual game world; that's probably the easiest way to add the cams. However there might be a more elegant solution :p

**Comment by vivandoshi08** [comment]
are you hosting your game on an aws ec2 or something else

**Comment by vivandoshi08** [comment]
also in security where is the code for clicking the camera screens.
