### ISSUE TITLE
Cameras

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#8]
Could you guys make a cameras function in Security please. I have been trying to for a while but couldn't due to some player camera errors.

**Comment by Twometer** [comment]
What errors are you getting?

**Comment by Twometer** [comment]
I added some basic cameras, however it'd also be cool to have blinking cameras in the map as well as some postproc.

**Comment by Twometer** [comment]
Post processing FX are actually in place now
