### ISSUE TITLE
servers are down

### ISSUE THREAD

**Issue by vivandoshi08** [Twometer/among-us-3d#9]
When running the game, I get the error, [ERROR] [28/11/20 20:08:08] [de.twometer.amongus.net.client.NetClient/connect] Cannot connect to the server: java.net.SocketTimeoutException: Connected, but timed out during TCP registration.
Note: Client#update must be called in a separate thread during connect.

Can you get the server running again

**Comment by Twometer** [comment]
Server crashed, I restarted it and will look into the bug
